### ISSUE TITLE
Thanks a lot 😊

### ISSUE THREAD

**Issue by fnfporterhi** [LEVIXDDLMAO/LeatherEngineHTML#1]
I honestly love leather engine, and I love having it now on HTML5! Thanks guys!

**Comment by LEVIXDDLMAO** [comment]
Well i shouldn't be getting the thanks, he should @SanicBTW

**Comment by SanicBTW** [comment]
yeah, anyways, i have to point out that in options and binds the engine has to load the assets so it may take a while until it loads; the same with freeplay though this one seems harder, it will preload every song to ram and eventually will eat your ram (if you are on a school chromebook like me which its capped to 4gb and having a basic cpu then the whole chromebook will slow down while trying to load songs)

**Comment by LEVIXDDLMAO** [comment]
Yeah i noticed that

**Comment by SanicBTW** [comment]
I could try to preload the songs when loading the game assets (first stage)

**Comment by LEVIXDDLMAO** [comment]
Yeah that might work but in a few can we work on the engine?

**Comment by SanicBTW** [comment]
I'm in bed mate, it's like 6 am almost

**Comment by LEVIXDDLMAO** [comment]
Nah its fine, tommorrow??

**Comment by SanicBTW** [comment]
Sure

**Comment by LEVIXDDLMAO** [comment]
Thx I wanna fix the song issue

**Comment by SanicBTW** [comment]
In totally sure that it only happens on HTML5

**Comment by LEVIXDDLMAO** [comment]
Maybe.. but ill stay up all night if i have to fix it

**Comment by LEVIXDDLMAO** [comment]
it might be the project.xml

**Comment by fnfporterhi** [comment]
1 whole year and i never closed this

**Comment by SanicBTW** [comment]
:v

**Comment by fnfporterhi** [comment]
:v
